"""empty message

Revision ID: 2abd549504d0
Revises: 5ec8085542df
Create Date: 2019-06-21 12:21:19.599037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abd549504d0'
down_revision = '5ec8085542df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id'),
    sa.UniqueConstraint('exercise_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    # ### end Alembic commands ###
